apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-consumer
  namespace: openclaw-platform
  labels:
    app: billing-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-consumer
  template:
    metadata:
      labels:
        app: billing-consumer
    spec:
      containers:
        - name: consumer
          image: 956045422469.dkr.ecr.us-west-2.amazonaws.com/openclaw-saas-billing-consumer:v0.1.1
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: AWS_DEFAULT_REGION
              value: "us-west-2"
          envFrom:
            - secretRef:
                name: platform-api-config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
