name: CI

on:
  push:
    branches: [cn]
  pull_request:
    branches: [cn]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: Add linting and tests
