apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: "tenant-{{ tenant_name }}"
spec:
  limits:
    - type: Container
      {% if plan == 'free' %}
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "250m"
        memory: "1Gi"
      max:
        cpu: "2"
        memory: "3Gi"
      {% elif plan == 'pro' %}
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "250m"
        memory: "1Gi"
      max:
        cpu: "4"
        memory: "8Gi"
      {% elif plan == 'enterprise' %}
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "500m"
        memory: "2Gi"
      max:
        cpu: "8"
        memory: "16Gi"
      {% elif plan == 'unlimited' %}
      default:
        cpu: "4"
        memory: "8Gi"
      defaultRequest:
        cpu: "1"
        memory: "4Gi"
      max:
        cpu: "32"
        memory: "64Gi"
      {% endif %}
