apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: "tenant-{{ tenant_name }}"
spec:
  limits:
    - type: Container
      {% if plan == 'free' %}
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
      max:
        cpu: "2"
        memory: "4Gi"
      {% elif plan == 'pro' %}
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
      max:
        cpu: "2"
        memory: "4Gi"
      {% elif plan == 'enterprise' %}
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "500m"
        memory: "2Gi"
      max:
        cpu: "4"
        memory: "8Gi"
      {% endif %}
