apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: "tenant-{{ tenant_name }}"
spec:
  hard:
    {% if plan == 'free' %}
    requests.cpu: "1"
    requests.memory: "4Gi"
    limits.cpu: "2"
    limits.memory: "6Gi"
    pods: "3"
    persistentvolumeclaims: "2"
    {% elif plan == 'pro' %}
    requests.cpu: "4"
    requests.memory: "16Gi"
    limits.cpu: "8"
    limits.memory: "24Gi"
    pods: "10"
    persistentvolumeclaims: "10"
    {% elif plan == 'enterprise' %}
    requests.cpu: "16"
    requests.memory: "64Gi"
    limits.cpu: "32"
    limits.memory: "96Gi"
    pods: "50"
    persistentvolumeclaims: "50"
    {% endif %}
