apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: "tenant-{{ tenant_name }}"
spec:
  hard:
    {% if plan == 'free' %}
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "3"
    persistentvolumeclaims: "3"
    {% elif plan == 'pro' %}
    requests.cpu: "8"
    requests.memory: "24Gi"
    limits.cpu: "24"
    limits.memory: "48Gi"
    pods: "15"
    persistentvolumeclaims: "15"
    {% elif plan == 'enterprise' %}
    requests.cpu: "24"
    requests.memory: "80Gi"
    limits.cpu: "120"
    limits.memory: "240Gi"
    pods: "60"
    persistentvolumeclaims: "60"
    {% endif %}
